const USER_DETAILS = "USER_DETAILS";
const CREATE_ACCOUNT = "CREATE_ACCOUNT";
const SIGN_OUT = "SIGN_OUT";
const INITIALIZE_GROUPS = "INITIALIZE_GROUPS";
const ADD_NEW_GROUP = "ADD_NEW_GROUP";


export {
    USER_DETAILS,
    CREATE_ACCOUNT,
    SIGN_OUT,
    INITIALIZE_GROUPS,
    ADD_NEW_GROUP
}
