const USER_DETAILS = "USER_DETAILS";
const CREATE_ACCOUNT = "CREATE_ACCOUNT";
const SIGN_OUT = "SIGN_OUT";
const INITIALIZE_GROUPS = "INITIALIZE_GROUPS";
const ADD_NEW_GROUP = "ADD_NEW_GROUP";
const FETCH_CONVERSATION = "FETCH_CONVERSATION";
const FETCH_NEW_MESSAGE = "FETCH_NEW_MESSAGE";
const CHANGE_PREV_DATE = "CHANGE_PREV_DATE";
const TOGGLE_FROMDATEPICKER = "TOGGLE_FROMDATEPICKER";
const TOGGLE_TODATEPICKER = "TOGGLE_TODATEPICKER";
const PICK_FROM_DATE = "PICK_FROM_DATE";
const PICK_TO_DATE = "PICK_TO_DATE";
const SET_GROUPID = "SET_GROUPID";
const CHANGE_TEXT = "CHANGE_TEXT";
const RESET_EVENT_TYPE = "RESET_EVENT_TYPE";
const TOGGLE_EVENT_MODAL = "TOGGLE_EVENT_MODAL";
const POPULATE_NOTATTENDING = "POPULATE_NOTATTENDING";
const POPULATE_ATTENDING = "POPULATE_ATTENDING";
const FETCH_GROUP = "FETCH_GROUP";
const SORT_GROUPS = "SORT_GROUPS";
const FETCH_EVENTS = "FETCH_EVENTS";
const CLEAR_EVENTS = "CLEAR_EVENTS";
const INCREMENT_COUNT = "INCREMENT_COUNT";
const SET_TO_ZERO = "SET_TO_ZERO";
const POPULATE_GROUPS = "POPULATE_GROUPS";
const STORE_PERSONAL_EVENTS = "STORE_PERSONAL_EVENTS";
const REMOVE_GROUP = "REMOVE_GROUP";
const REMOVE_GROUP_EVENTS = "REMOVE_GROUP_EVENTS";
const REMOVE_GROUP_MESSAGES = "REMOVE_GROUP_MESSAGES";
const REMOVE_USER_FROM_GROUP_REDUX = "REMOVE_USER_FROM_GROUP_REDUX";
const ADD_MEMBER_TO_GROUP = "ADD_MEMBER_TO_GROUP";

export {
  ADD_MEMBER_TO_GROUP,
  REMOVE_GROUP_MESSAGES,
  REMOVE_USER_FROM_GROUP_REDUX,
  REMOVE_GROUP_EVENTS,
  POPULATE_GROUPS,
  REMOVE_GROUP,
  SET_TO_ZERO,
  INCREMENT_COUNT,
  CLEAR_EVENTS,
  FETCH_EVENTS,
  SORT_GROUPS,
  USER_DETAILS,
  CREATE_ACCOUNT,
  SIGN_OUT,
  INITIALIZE_GROUPS,
  ADD_NEW_GROUP,
  FETCH_CONVERSATION,
  FETCH_NEW_MESSAGE,
  CHANGE_PREV_DATE,
  TOGGLE_TODATEPICKER,
  TOGGLE_FROMDATEPICKER,
  PICK_FROM_DATE,
  PICK_TO_DATE,
  SET_GROUPID,
  CHANGE_TEXT,
  RESET_EVENT_TYPE,
  TOGGLE_EVENT_MODAL,
  POPULATE_NOTATTENDING,
  POPULATE_ATTENDING,
  FETCH_GROUP,
  STORE_PERSONAL_EVENTS,
};
